version: 2

before:
  hooks:

builds:
  -
    main: ./
    binary: ssd
    id: ssd
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64
      - mips64
    goarm:
      - "7"

release:
  draft: false

archives:
  -
    id: "ssd"
    builds: ['ssd']
    formats:
      - tar.gz
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

nfpms:
  -
    id: "ssd"
    builds: ['ssd']
    formats:
      - deb
      - rpm
    vendor: "Greenline Software LLC<info@greenline-software.com>"
    homepage: "https://greenline-software.com/"
    maintainer: "Dimitriy Kuschel <info@greenline-software.com>"

    description: "ssd"
    license: "Apache 2.0"
    file_name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    bindir: /usr/sbin

    dependencies:
      - systemd
      - logrotate

    contents:

      - dst: "/etc/ssd"
        type: dir

      - dst: "/var/log/ssd"
        type: dir

      - src: "deployments/systemd/ssd.service"
        dst: "/lib/systemd/system/ssd.service"

      - src: "deployments/logrotate.d/ssd"
        dst: "/etc/logrotate.d/ssd"

      - src: "configs/config-release.yml"
        dst: "/etc/ssd/config.yml"
        type: config


    scripts:
      postinstall: "scripts/postinstall.sh"

snapshot:
  name_template: "{{.Version}}-master"
changelog:
  sort: asc
  filters:
    exclude:
    - README
    - OPTIONS
    - Readme
    - Options
    - Image
    - Script
    - Docker
    - Typo
    - "via upload"
    - goreleaser
