// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"ssd/internal"
	"ssd/internal/controllers"
	"ssd/internal/providers"
	"ssd/internal/services"
	"ssd/internal/statistic"
	"ssd/internal/structures"
)

// Injectors from injectors.go:

func InitApp(cfg *structures.CliFlags) (*internal.App, error) {
	config, err := providers.NewConfigProvider(cfg)
	if err != nil {
		return nil, err
	}
	statisticServiceInterface := services.NewStatisticService(config)
	healthController := controllers.NewHealthController(statisticServiceInterface)
	logger, err := providers.NewLogProvider(config)
	if err != nil {
		return nil, err
	}
	compressorInterface, err := statistic.NewZstdCompressor()
	if err != nil {
		return nil, err
	}
	fileManager := statistic.NewFileManager(compressorInterface, statisticServiceInterface, logger)
	metricsProviderInterface := providers.NewMetricsProvider(config, statisticServiceInterface)
	cacheProviderInterface := providers.NewInstrumentedCacheProvider(config, logger, metricsProviderInterface)
	schedulerInterface := statistic.NewScheduler(config, logger, statisticServiceInterface, fileManager, metricsProviderInterface, cacheProviderInterface)
	apiController := controllers.NewApiController(logger, statisticServiceInterface, cacheProviderInterface)
	serveMux := internal.InitRoutes(apiController)
	app, err := internal.NewApp(healthController, schedulerInterface, config, logger, serveMux, metricsProviderInterface)
	if err != nil {
		return nil, err
	}
	return app, nil
}
